# Generated by Django 5.1.1 on 2024-12-13 10:20

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='barber',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='barber',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], max_length=27),
        ),
    ]
